name: testis

env:
  REGISTRY_IMAGE: ghcr.io/prokleta-kuja/testis

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag image with'
        required: true
        default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - 
      name: Restore dependencies
      run: dotnet restore
    - 
      name: Build
      run: dotnet build --no-restore
    - 
      name: Publish
      run: dotnet publish poc_arm64.csproj /p:Version=$Version -c Release --no-restore -o app
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.REGISTRY_IMAGE }}:latest
          ${{ env.REGISTRY_IMAGE }}:${{ github.event.inputs.version }}